const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const INCREMENTOIMPAR = 'INCREMENTOIMPAR';
const INCREMENTOASYNC = 'INCREMENTOASYNC';

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTOIMPAR,
  INCREMENTOASYNC
}